server:
  port: 8084

jwt:
  access-token:
    expired: 3600000         # 1시간
    secret-key: "h0t4hiw4hj94w595j9w4yi9dsnvkbxzmcxbn2e3r23"
  refresh-token:
    expired: 86400000        # 1일
    secret-key: "q1opwdjqprpqweeqpe3905y9056055--htndkondv"


cors:
  allowed-origins:
    - "http://localhost:3000"
  allowed-headers:
    - "*"
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS

app:
  redis:
    prefix:
      refresh: "ctrlline:refresh:"
      blacklist: "ctrlline:refresh:"

spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/ctrlline"
    username: beyond
    password: beyond
    driver-class-name: org.mariadb.jdbc.Driver
  # Flyway
  flyway:
    enabled: false
    locations: classpath:db/migration
  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      password: beyond
  # Jpa
  jpa:
    hibernate:
      ddl-auto: update # Flyway로 테이블 관리하므로 JPA는 validate로
    show-sql: true

logging:
  level:
    com.beyond.synclab.ctrlline.**: debug

