server:
  port: 8080

jwt:
  access-token:
    expired: ${ACCESS_TOKEN_EXPIRED}
    secret-key: ${ACCESS_TOKEN_SECRET}
  refresh-token:
    expired: ${REFRESH_TOKEN_EXPIRED}
    secret-key: ${REFRESH_TOKEN_SECRET}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS} # 운영 프론트 주소
  allowed-headers:
    - Authorization
    - Content-Type
    - Accept
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS

app:
  redis:
    prefix:
      refresh: "ctrlline:refresh:"
      blacklist: "ctrlline:refresh:"

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  # Jpa
  jpa:
    hibernate:
      ddl-auto: validate # Flyway로 테이블 관리하므로 JPA는 validate로
    show-sql: true